# Generated by Django 4.1 on 2022-08-31 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shark_conservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shark',
            name='added_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shark',
            name='description',
            field=models.TextField(blank=True, default=' ', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='shark',
            name='location',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
