# Generated by Django 4.1 on 2022-08-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shark_conservation_app', '0003_remove_shark_description_shark_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shark',
            name='info',
        ),
        migrations.AddField(
            model_name='shark',
            name='description',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
